# SPDX-License-Identifier: GPL-2.0-only
# Makefile for sysfs selftests.

# No binaries, but make sure arg-less "make" doesn't trigger "run_tests".
all:

TEST_PROGS := sysfs.sh

include ../lib.mk

# Nothing to clean up.
clean:
